services:

  db:
    image: postgres:16
    container_name: hireflow_db
    restart: unless-stopped

    environment:
      POSTGRES_USER: karuabrian
      POSTGRES_PASSWORD: Karuabrian.2002
      POSTGRES_DB: job_board

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data  

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U karuabrian -d job_board -h localhost -p 5432"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path", "/migrations",
        "-database",
        "postgres://karuabrian:Karuabrian.2002@db:5432/job_board?sslmode=disable",
        "up"
      ]      
    restart: "no"  
  api: 
    build: .
    container_name: hireflow_api

    depends_on:
      migrate:
        condition: service_healthy
      db:
        condition: service_healthy 

    environment:
      - DB_USER=karuabrian
      - DB_PASSWORD=Karuabrian.2002
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=job_board
      - DB_DSN=postgres://karuabrian:Karuabrian.2002@db:5432/job_board?sslmode=disable
      - JWT_SECRET=SUPER_SECRET_KEY
      - PORT=8080

    ports:
      - "8080:8080"    

    restart: unless-stopped

volumes:
    postgres_data:
