version: "5.0"

services:

  db:
    image: postgres:16
    container_name: hireflow_db
    restart: always
    environment:
      POSTGRES_USER: karuabrian
      POSTGRES_PASSWORD: Karuabrian.2002
      POSTGRES_DB: job_board
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  

  migrate: 
    image: migrate/migrate

    depends_on:
      - db
  
    volumes:
      - ./migrations:/migrations

    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://karuabrian:Karuabrian.2002@db:5432/job_board?sslmode=disable",
        "up"
      ]  

  api: 
    build: .
    container_name: hireflow_api
    depends_on:
      - db
      - migrate
    environment:
      - DB_USER=karuabrian
      - DB_PASSWORD=Karuabrian.2002
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=job_board
      - DB_DSN=postgres://karuabrian:password@db:5432/hireflow_db?sslmode=disable
      - JWT_SECRET=SUPER_SECRET_KEY
      - PORT=8080
    ports:
      - "8080:8080"    
    restart: always

volumes:
    postgres_data:
